name: mon_app_getx
description: "Orange Money Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  mailer: ^6.0.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.5
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  get: ^4.7.2
  camera: ^0.11.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
